<a href="https://colab.research.google.com/github/indra622/AIAcademy_SpeechRecognition/blob/main/2_1_basic_MLP_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 기초 MLP 모델 실습


### import

In [2]:
import torch
import torch.nn as nn

### device check

In [8]:
torch.cuda.is_available()

device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [6]:
device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')

In [7]:
device

device(type='cuda')

## XOR 문제

Train Sample 

<img src="https://github.com/indra622/AIAcademy_SpeechRecognition/raw/main/img/xor_input.jpg" width=200>

In [9]:
X = [[0,0], [0,1], [1,0], [1,1]]
Y = [[0],[1],[1],[0]]

In [16]:
X = torch.tensor(X,dtype=torch.float)
Y = torch.tensor(Y,dtype=torch.float)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  


In [17]:
X,Y

(tensor([[0., 0.],
         [0., 1.],
         [1., 0.],
         [1., 1.]]), tensor([[0.],
         [1.],
         [1.],
         [0.]]))

In [18]:
X.dtype

torch.float32

### Perceptron
<img src="https://raw.githubusercontent.com/indra622/AIAcademy_SpeechRecognition/main/img/perceptron.jpg" width=400>

In [19]:
model = nn.Sequential(
    nn.Linear(2,1,bias=True),
    nn.Sigmoid()
)

In [20]:
model

Sequential(
  (0): Linear(in_features=2, out_features=1, bias=True)
  (1): Sigmoid()
)

### loss function and optimizer


In [28]:
loss_fn = torch.nn.BCELoss()
optim = torch.optim.SGD(model.parameters(),lr = 0.01)

### train loop
- epoch (전체 데이터)

  - batch (전체 데이터의 부분집합)


In [29]:
model(X)

tensor([[0.5034],
        [0.6718],
        [0.5558],
        [0.7165]], grad_fn=<SigmoidBackward0>)

0 -> False 

1 -> True

In [35]:
from tqdm.auto import tqdm #progress bar 형식으로 loop의 진행상황을 확인가능

In [37]:
import time
for _ in tqdm(range(100)):
  time.sleep(0.1)

  0%|          | 0/100 [00:00<?, ?it/s]

In [39]:
n_epoch = 10000
loss_fn = torch.nn.BCELoss()
optim = torch.optim.SGD(model.parameters(),lr = 0.01)

model.to(device)
X = X.to(device)
Y = Y.to(device)

for epoch in tqdm(range(n_epoch)):
  #for batch in train_loader()
  optim.zero_grad()    # gradient 초기화
  pred = model(X)
  loss = loss_fn(pred,Y) # loss(prediction, GT) 
  if epoch %1000 == 0 : 
    print(loss)
  loss.backward()       # back propagation gradient 계산
  optim.step()          # Weight Update




  0%|          | 0/10000 [00:00<?, ?it/s]

tensor(0.6931, device='cuda:0', grad_fn=<BinaryCrossEntropyBackward0>)
tensor(0.6931, device='cuda:0', grad_fn=<BinaryCrossEntropyBackward0>)
tensor(0.6931, device='cuda:0', grad_fn=<BinaryCrossEntropyBackward0>)
tensor(0.6931, device='cuda:0', grad_fn=<BinaryCrossEntropyBackward0>)
tensor(0.6931, device='cuda:0', grad_fn=<BinaryCrossEntropyBackward0>)
tensor(0.6931, device='cuda:0', grad_fn=<BinaryCrossEntropyBackward0>)
tensor(0.6931, device='cuda:0', grad_fn=<BinaryCrossEntropyBackward0>)
tensor(0.6931, device='cuda:0', grad_fn=<BinaryCrossEntropyBackward0>)
tensor(0.6931, device='cuda:0', grad_fn=<BinaryCrossEntropyBackward0>)
tensor(0.6931, device='cuda:0', grad_fn=<BinaryCrossEntropyBackward0>)


In [40]:
model(X)

tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], device='cuda:0', grad_fn=<SigmoidBackward0>)

### MLP 
<img src="https://raw.githubusercontent.com/indra622/AIAcademy_SpeechRecognition/main/img/MLP.jpg" width=200>